### ISSUE TITLE
Unknown custom element: <vue-telegram-login> - did you register the component correctly?

### ISSUE THREAD

**Issue by mmmykhailo** [vchaptsev/vue-telegram-login#3]
### I have this error
[Vue warn]: Unknown custom element: <vue-telegram-login> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Login> at src/components/Login.vue
       <App> at src/App.vue
         <Root>

### my Login.vue
<template>
  
  
  <vue-telegram-login 
    mode="callback"
    telegram-login="sqwtgbot"
    @callback="yourCallbackFunction" />
  
</template>

<script>
import {vueTelegramLogin} from 'vue-telegram-login'

export default {
  name: 'Login',
  components: {vueTelegramLogin},
  methods: {
    yourCallbackFunction (user) {
      // gets user as an input
      // id, first_name, last_name, username,
      // photo_url, auth_date and hash
      console.log(user)
    }
  }
}
</script>

### my router/index.js
import Vue from 'vue'
import Router from 'vue-router'
import HelloWorld from '@/components/HelloWorld'
import LoginP from '@/components/Login'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'HelloWorld',
      component: HelloWorld
    },
    {
      path: '/login',
      name: 'LoginP',
      component: LoginP
    }
  ]
})

### my main.js
import Vue from 'vue'
import App from './App'
import router from './router'

Vue.config.productionTip = false

new Vue({
  el: '#app',
  router,
  components: { App },
  template: '<App/>'
})

### my App.vue
<template>
  <div id="app">
    <router-view/>
  </div>
</template>

<script>
export default {
  name: 'App'
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

**Comment by vchaptsev** [comment]
Hey, @sqwoteg 
Thank you for the issue!

Fixed in version `2.0.0`
Please update `vue-telegram-login` and provide feedback

**Comment by mmmykhailo** [comment]
Tnx for the reply.
Now it says "Bot domain invalid"
Does it work on 8080 port?

**Comment by vchaptsev** [comment]
Unfortunately, Telegram does not allow the use of localhost :(

P.S. you must send the `/setdomain` command to **Botfather** to link your website's domain to the bot.
