### ISSUE TITLE
Mention that third party (Telegram) cookies should be enabled

### ISSUE THREAD

**Issue by robverhoef** [vchaptsev/vue-telegram-login#5]
What you did:
Followed the ReadMe

What happened:
Callback didn't get called at all

Problem description:
This method does not work without allowing third party cookies -from Telegram-.
https://stackoverflow.com/a/52918944/548907

Suggested solution:
Mention this in the ReadMe; it will save a few developer-hours in some cases.

**Comment by vchaptsev** [comment]
Hey, @robverhoef 
I mentioned it in the README.md.
Thanks 👍
